routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MixerController;
use App\Http\Controllers\VideoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__.'/auth.php';

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::resources([
//    '/' => HomeController::class,
 //   '/home' => HomeController::class,
//    '/about' => AboutController::class,
    '/history' => HistoryController::class,
//    '/videos' => VideoController::class,
    '/cards' => \App\Http\Controllers\CardController::class
 ]);
Route::get('/mixers', MixerController::class)->name('mixers.index');
Route::get('/', HomeController::class);
Route::post('/', HomeController::class);
Route::get('/contact',ContactController::class)->name('contact.index');
Route::post('/contact',EmailController::class);

Route::get('/home', HomeController::class)->name('home.index');
Route::get('/about/index', [AboutController::class, 'index'])->name('about.index');
Route::get('/about/gunite', [AboutController::class, 'gunite'])->name('about.gunite');
Route::get('/about/strengths', [AboutController::class, 'strengths'])->name('about.strengths');
Route::get('/videos', VideoController::class)->name('videos.index');
Route::get('/applications', function() {
   return view('pages.applications');
})->name('applications.index');

app/Http/Controllers/AboutController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\View as V;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function strengths() {
        return view('pages.about.strength', [
            'view' => V::find(5)
        ]);
    }

    public function gunite() {
        return view('pages.about.gunite', [
            'view' => V::find(6)
        ]);
    }

    public function equipment() {
        return view('pages.about.equipment', [
            'view' => V::find(6)
        ]);
    }
}

resources/views/pages/about/about.blade.php
About Page

resources/views/pages/about/equipment.blade.php
<x-container-fluid class="h-100 mx-0 border-0 mt-5 px-0 flex-column" bgSrc="/images/infrastruture.png">
<x-card.card :card="$view->cards[1]" class="my-3 col-8 offset-2">
</x-card.card>

</x-container-fluid>

resources/views/pages/about/gunite.blade.php
<x-container-fluid class="h-100 mx-0 border-0 mt-5 px-0 flex-column" bgSrc="/images/infrastruture.png">
<x-card.card :card="$view->cards[0]" class="my-3 col-8 offset-2">
</x-card.card>

</x-container-fluid>

resources/views/pages/about/history.blade.php
<x-container-fluid class="h-100 mx-0 border-0 mt-5 px-0 flex-column" bgSrc="/images/infrastruture.png">
    <x-flex-row class="justify-content-center mx-auto">
        <x-card.card class="mt-5 col-12 col-md-4">
            <x-card.header class="d-flex flex-row">
                <x-card.title>
                    The Strong Gunite Advantage
                </x-card.title>
                <x-auth-button-edit class="my-3">Edit</x-auth-button-edit>
            </x-card.header>
            <x-card.body class="justify-content-between p-0">
                <x-flex-row>
                    <img class='card-img w-75 flex-shrink-1' src="/images/truck.png" />
                    <x-flex-column>
                        <x-card.card class="flex-grow-1">
                            <x-card.header class="bg-light">
                                <h4 class="card-title">Capacities</h4>
                            </x-card.header>
                            <x-card.body class="px-2">
                                <ul>
                                    <li>Cement: 85ft<sup>3</sup></li>
                                    <li>Sand: 378ft<sup>3</sup></li>
                                    <li>Total: 14yds<sup>3</sup></li>
                                </ul>
                            </x-card.body>
                        </x-card.card>

                        <x-card.card class="flex-grow-1">
                            <x-card.header class="bg-light">
                                <h4 class="card-title">Dimensions</h4>
                            </x-card.header>
                            <x-card.body class="px-2">
                                <ul>
                                    <li>Cement: 97'</li>
                                    <li>Sand: 97'</li>
                                    <li>Total: 19ft</li>
                                </ul>
                            </x-card.body>
                        </x-card.card>
                    </x-flex-column>
                </x-flex-row>
            </x-card.body>
        </x-card.card>
    </x-flex-row>
    <div class="card-group mt-3">
        <x-card.card class="mx-3">
            <x-card.header >
                <x-card.title>
                    User Friendly Controls
                </x-card.title>
                <x-auth-button-edit class="my-3">Edit</x-auth-button-edit>
            </x-card.header>
            <x-card.body class="justify-content-between p-0">
                <x-flex-row class="justify-content-between">
                    <img class='card-img w-100' src="/images/controls.png" />
                    <x-card.card class="flex-shrink-1">
                        <x-card.body>Simple Levers and Hydraulic Circuits provide virtually effortless control of all functions of the mixer. </x-card.body>
                    </x-card.card>
                </x-flex-row>
            </x-card.body>
        </x-card.card>
        <x-card.card class="mx-3">
            <x-card.header >
                <x-card.title>
                    Maximum Payload
                </x-card.title>
                <x-auth-button-edit class="my-3">Edit</x-auth-button-edit>
            </x-card.header>
            <x-card.body class="justify-content-between p-0">
                <x-flex-row class="justify-content-between">

                    <img class='card-img' src="/images/max_payload.png" />
                    <x-card.card class="flex-shrink-1">
                        <x-card.body>Simple Levers and Hydraulic Circuits provide virtually effortless control of all functions of the mixer. </x-card.body>
                    </x-card.card>
                </x-flex-row>
            </x-card.body>
        </x-card.card>

        <x-card.card class="mx-3">
            <x-card.header >
                <x-card.title>
                    Optimized Design
                </x-card.title>
                <x-auth-button-edit class="my-3">Edit</x-auth-button-edit>
            </x-card.header>
            <x-card.body class="justify-content-between p-0">
                <x-flex-row class="justify-content-between">

                    <img class='card-img' src="/images/optimized_design.png" />
                    <x-card.card class="flex-shrink-1">
                        <x-card.body>Simple Levers and Hydraulic Circuits provide virtually effortless control of all functions of the mixer. </x-card.body>
                    </x-card.card>
                </x-flex-row>
            </x-card.body>
        </x-card.card>
    </div>
    <x-flex-row class="justify-content-center w-100 my-5">
        <x-card.card class="mt-5 col-5">
            <x-card.header >
                <x-card.title>
                    Your Single Source for Complete Gunite Systems
                </x-card.title>
                <x-auth-button-edit class="my-3">Edit</x-auth-button-edit>
            </x-card.header>
            <x-card.body class="justify-content-between p-0">
                <x-flex-row class="justify-content-between">
                    <img class='card-img w-75 flex-shrink-1' src="/images/compressor_setup.png" />
                    <x-card.card class="flex-shrink-1">
                        <x-card.body>
                            <p>
                                <a href="{{ route('history.index') }}">We have experience in the gunite industry.</a> From contractor work to manufacturing, even going back to our franchising days. This means we know what to expect with every facet of the business and can supply new clients and seasoned veterans alike with every piece of equipment a gunite business needs, all held to the highest standards.</p> </x-card.body>
                    </x-card.card>
                </x-flex-row>
            </x-card.body>
        </x-card.card>
    </x-flex-row>
</x-container-fluid>

resources/views/pages/about/strength.blade.php
<div class="py-4"></div>
@include('pages.mixers.viewer')
{{--    <x-flex-row class="justify-content-center">
    <div class="card-group mt-3 col-10">
        <x-card.card class="mx-3">
            <x-card.header >
                <x-card.title>
                    User Friendly Controls
                </x-card.title>
                <x-auth-button-edit class="my-3">Edit</x-auth-button-edit>
            </x-card.header>
            <x-card.body class="justify-content-between p-0">
                <x-flex-row class="justify-content-between my-0 h-100">
                <img class='card-img flex-shrink-1 bg-black' src="/images/controls.png" />
                <x-card.card class="w-50 flex-fill">
                    <x-card.body>Simple Levers and Hydraulic Circuits provide virtually effortless control of all functions of the mixer. </x-card.body>
                </x-card.card>
                </x-flex-row>
            </x-card.body>
        </x-card.card>
        <x-card.card class="mx-3">
            <x-card.header >
                <x-card.title>
                    Maximum Payload
                </x-card.title>
                <x-auth-button-edit class="my-3">Edit</x-auth-button-edit>
            </x-card.header>
            <x-card.body class="justify-content-between p-0">
                <x-flex-row class="justify-content-between">

                <img class='card-img w-75' src="/images/max_payload.png" />
                <x-card.card class="w-25">
                    <x-card.body>Simple Levers and Hydraulic Circuits provide virtually effortless control of all functions of the mixer. </x-card.body>
                </x-card.card>
                </x-flex-row>
            </x-card.body>
        </x-card.card>

        <x-card.card class="mx-3">
            <x-card.header >
                <x-card.title>
                    Optimized Design
                </x-card.title>
                <x-auth-button-edit class="my-3">Edit</x-auth-button-edit>
            </x-card.header>
            <x-card.body class="justify-content-between p-0">
                <x-flex-row class="justify-content-between">

                <img class='card-img w-75' src="/images/optimized_design.png" />
                <x-card.card class="w-25">
                    <x-card.body>Simple Levers and Hydraulic Circuits provide virtually effortless control of all functions of the mixer. </x-card.body>
                </x-card.card>
                </x-flex-row>
            </x-card.body>
        </x-card.card>
    </div>
    </x-flex-row>
    <x-flex-row class="justify-content-center w-100 mt-3 mb-5">
        <x-card.card class="mt-5 col-10">
            <x-card.header >
                <x-card.title>
                    Your Single Source for Complete Gunite Systems
                </x-card.title>
                <x-auth-button-edit class="my-3">Edit</x-auth-button-edit>
            </x-card.header>
            <x-card.body class="justify-content-between p-0">
                <x-flex-row class="justify-content-between">
                    <img class='card-img w-25' src="/images/compressor_setup.png" />
                    <x-card.card class="w-75">
                            <x-card.body>
                                <p>
                                    <a href="{{ route('history.index') }}">We have experience in the gunite industry.</a> From contractor work to manufacturing, even going back to our franchising days. This means we know what to expect with every facet of the business and can supply new clients and seasoned veterans alike with every piece of equipment a gunite business needs, all held to the highest standards.</p>
                                    <x-card.card :card="$view->cards[0]" class="flex-fill">
                                    </x-card.card>

                            </x-card.body>
                        </x-card.card>
                    </x-flex-row>
            </x-card.body>
        </x-card.card>
    </x-flex-row>--}}